### ISSUE TITLE
Thread safety issue in taggers

### ISSUE THREAD

**Issue by qadam** [ppke-nlpg/purepos#8]
Hi,

I want to use the taggers in multi threaded environment but they throws exceptions

```
java.lang.ArrayIndexOutOfBoundsException: 2
	at java.util.ArrayList.add(ArrayList.java:459)
	at hu.ppke.itk.nlpg.purepos.common.AnalysisQueue.init(AnalysisQueue.java:79)

java.lang.NullPointerException
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:234)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
	at java.util.ArrayList.add(ArrayList.java:458)
	at hu.ppke.itk.nlpg.purepos.common.AnalysisQueue.init(AnalysisQueue.java:79)
```

`hu.ppke.itk.nlpg.purepos.common.Util` should not hold a non thread-safe `AnalysisQueue` in static variable

Both `MorphTagger` and `POSTagger` want to modify the state of this variable which cause the trouble

**Comment by qadam** [comment]
I've made a unit test to validate the issue: [Test case for thread-safety in Util](https://github.com/qadam/purepos/commit/b8c1f06c20453a97297241cb4f74515b51c88198)

**Comment by dlazesz** [comment]
Thank your for your contribution!
